name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5.0.0
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
